version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: human_crossing_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: human_crossing
      POSTGRES_PASSWORD: human_crossing
      POSTGRES_DB: human_crossing
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
